// @ts-nocheck
// eslint-disable 
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/vite-plugin-router
// https://github.com/felipe-bergamaschi/vite-router

import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import type { RouteProps } from 'vite-plugin-router';

const Route0 = lazy(() => import('../pages/a/b/c'));
const Route1 = lazy(() => import('../pages/a/b/index'));
const Route3 = lazy(() => import('../pages/d/[name]'));
const Layout2 = lazy(() => import('../pages/a/layout'));

/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/vite-plugin-router
 * @link https://github.com/felipe-bergamaschi/vite-router
 */
export function AppRoutes(props: RouteProps) {
  return (
    <BrowserRouter>
      <Suspense fallback={props.loadingPage || <div>Loading...</div>}>
        <Routes>

<Route path={"/a/b/c"} key={"/a/b/c"} element={<Layout2><Route0></Route0></Layout2>}></Route>
<Route path={"/a/b"} key={"/a/b"} element={<Layout2><Route1></Route1></Layout2>}></Route>
<Route path={"/d/:name"} key={"/d/:name"} element={<Route3></Route3>}></Route>

          <Route
            path="*"
            element={props.notFoundPage || <div>404</div>}
          />
        </Routes>
      </Suspense> 
    </BrowserRouter>
  );
}