// @ts-nocheck
// eslint-disable 
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/vite-plugin-router
// https://github.com/felipe-bergamaschi/vite-router

import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import type { RouteProps } from 'vite-plugin-router';

const R0 = lazy(() => import('./app/admin/'));
const R2 = lazy(() => import('./app/admin/product/details/[id]/'));
const R3 = lazy(() => import('./app/admin/product/[id]'));
const R4 = lazy(() => import('./app/'));
const L1 = lazy(() => import('./app/admin/layout'));
const L5 = lazy(() => import('./app/layout'));

/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/vite-plugin-router
 * @link https://github.com/felipe-bergamaschi/vite-router
 */
export function AppRoutes(props: RouteProps) {
  return (
    <BrowserRouter>
      <Suspense fallback={props.loadingPage || <div>Loading...</div>}>
        <Routes>
          <Route path={"/admin"} key={"/admin"} element={<L1><R0></R0></L1>}></Route>
<Route path={"/admin/product/details/[id]"} key={"/admin/product/details/[id]"} element={<L1><R2></R2></L1>}></Route>
<Route path={"/admin/product/:id"} key={"/admin/product/:id"} element={<L1><R3></R3></L1>}></Route>
<Route path={"/"} key={"/"} element={<L5><R4></R4></L5>}></Route>
          <Route
            path="*"
            element={props.notFoundPage || <div>404</div>}
          />
        </Routes>
      </Suspense> 
    </BrowserRouter>
  );
}