// @ts-nocheck
// eslint-disable 
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/vite-plugin-router
// https://github.com/felipe-bergamaschi/vite-router

import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import type { RouteProps } from 'vite-plugin-router';

const Route0 = lazy(() => import('./app/admin/index'));
const Route2 = lazy(() => import('./app/admin/product/details/[id]/index'));
const Route3 = lazy(() => import('./app/admin/product/[id]'));
const Route4 = lazy(() => import('./app/index'));
const Route6 = lazy(() => import('./app/styles'));
const Layout1 = lazy(() => import('./app/admin/layout'));
const Layout5 = lazy(() => import('./app/layout'));

/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/vite-plugin-router
 * @link https://github.com/felipe-bergamaschi/vite-router
 */
export function AppRoutes(props: RouteProps) {
  return (
    <BrowserRouter>
      <Suspense fallback={props.loadingPage || <div>Loading...</div>}>
        <Routes>
          <Route path={"/admin"} key={"/admin"} element={<Layout1><Route0></Route0></Layout1>}></Route>
<Route path={"/admin/product/details/[id]"} key={"/admin/product/details/[id]"} element={<Layout1><Route2></Route2></Layout1>}></Route>
<Route path={"/admin/product/:id"} key={"/admin/product/:id"} element={<Layout1><Route3></Route3></Layout1>}></Route>
<Route path={"/"} key={"/"} element={<Layout5><Route4></Route4></Layout5>}></Route>
<Route path={"/styles"} key={"/styles"} element={<Layout5><Route6></Route6></Layout5>}></Route>
          <Route
            path="*"
            element={props.notFoundPage || <div>404</div>}
          />
        </Routes>
      </Suspense> 
    </BrowserRouter>
  );
}